@startuml
autonumber
participant program #white
participant update #white
participant view #white

program -> view : Renderiza a view
|||
view -> program : Aciona mensagem ex. Expand
program -> update : Envia mensagem com estado atual
update --> program : Retorna estado atualizado e comando
program -> view : Renderiza a view
@enduml
